### ISSUE TITLE
Failure after creating a new instance

### ISSUE THREAD

**Issue by pinkerunicorn** [Schnittcher/IPS-DeviceMonitor#6]
Fatal error: Uncaught Error: Call to undefined method DeviceMonitor::RegisterProfileIntegerEx() in /var/lib/symcon/modules/.store/info.schnittcher.ips.devicemonitor/IPS-DeviceMonitor/module.php:87
Stack trace:
#0 /var/lib/symcon/modules/.store/info.schnittcher.ips.devicemonitor/IPS-DeviceMonitor/module.php(24): DeviceMonitor->RegisterVariablenProfiles()
#1 /-(3): DeviceMonitor->Create()
#2 {main}
  thrown in /var/lib/symcon/modules/.store/info.schnittcher.ips.devicemonitor/IPS-DeviceMonitor/module.php on line 87
 (Code: -32603)

**Comment by Schnittcher** [comment]
Gefixt.
